<?php

/** @var \Unbxd\SearchJs\Block\Configuration $block */

$autoSuggestEnabled = $block->isAutoSuggestEnabled();
$configuration = $block->getConfiguration();
?>
<script type="text/javascript">
 UnbxdSiteName="<?php echo $configuration["credentials"]["siteName"]; ?>";
 UnbxdApiKey="<?php echo $configuration["credentials"]["apiKey"]; ?>";
 window.unbxdMagentoConfig = <?php /* @noEscape */echo json_encode($configuration); ?>;
</script>



<?php
/** Unbxd Analytics section */
$analyticsEnabled = $block->isAnalyticsEnabled();
if ($analyticsEnabled): ?>
<script type="text/javascript">

    UnbxdAnalyticsConf = window.UnbxdAnalyticsConf || {};

    var jsfiles = <?php echo '["'.$configuration["analytics"]["sdkUrl"].'","' . $configuration["analytics"]["jsUrl"] . '"]' ?>;
		        
            jsfiles.forEach(function(file,index) {
              if(file != "#"){
                    var s1 = document.createElement('script');
                    s1.type = 'text/javascript';
                    s1.async = true;
                    s1.src = file;
                    (document.getElementsByTagName('body')[0]).appendChild(s1);
              }
              });

</script>
<?php endif;?>

<?php /** Recommendations */
$recommendationEnabled = $block->isRecommendationEnabled();
if ($recommendationEnabled): ?>
<script type="text/javascript">

var jsfiles = <?php echo '["' . $configuration["recommendation"]["sdkUrl"] . '"]' ?>;
        
        jsfiles.forEach(function(file,index) {
                var s1 = document.createElement('script');
                s1.type = 'text/javascript';
                s1.async = true;
                s1.src = file;
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(s1);

          });
require(['jquery'],function($){

  $(document).ready(function(){
      var $rexContainers = $('.unbxd-recommendation-marker-js');
      var widgets = {};
      if ($rexContainers.length > 0 && "unbxd_recommendation_pageInfo" in window){
        $rexContainers.each(function(index,value){
          if ($(value).data('container')){
          widgets[$(value).data('container')] = {
            "name": value.id
          }
          }
        });
      var rexObj = {
        "widgets" : widgets,
         "userInfo": {
                userId: u_readCookie("unbxd.userId"),
                siteKey: UnbxdSiteName,
                apiKey: UnbxdApiKey
            },
          "pageInfo":unbxd_recommendation_pageInfo,
          itemClickHandler: function (product) {
                if('url' in product){
                  window.location=product.url;
                }else if ('productUrl' in product){
                  window.location=product.productUrl;
                }else{
                  console.warn("product url not available so click through will not happen in recommendations carousel.")
                }
            }
      }
      initRecommendation.call({counter:0});
      }
      function u_decodeAndParse(s) {
            if (s.indexOf('"') === 0) {
              // This is a quoted cookie as according to RFC2068, unescape...
              s = s.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\');
            }
            return u_decodeCookie(s);
          }
          function u_decodeCookie(s) {
            var pluses = /\+/g;
            return decodeURIComponent(s.replace(pluses, ' '));
          }

      function u_readCookie(key) {
            // Read
            var cookies = document.cookie.split('; ');
            var result;
            for (var i = 0, l = cookies.length; i < l; i++) {
                var parts = cookies[i].split('=');
                var name = u_decodeAndParse(parts.shift());
                var cookie = parts.join('=');
                if (key && key === name) {
                    try {
                        result = u_decodeAndParse(cookie);
                        break;
                    } catch (e) {
                        this.log(e);
                    }
                }
            }
            return result;
        }

      
      function initRecommendation(){

        if ("_unbxd_getRecommendations" in window){
          _unbxd_getRecommendations(rexObj);
        }else{
          if (this.counter < 10){
            setTimeout(initRecommendation.bind({counter:this.counter+1}), 1000);
          }else{
            console.log("Takes longer to load recommendations sdk");
          }
        }
        
      }

  });

});

</script>


<?php endif;?>

<?php /** Unbxd Autosuggest section */
if ($autoSuggestEnabled): ?>
<script type="text/javascript">

require(
            [
                'jquery',
                'handlebars'
            ],
            function (
                jQueryMain,
                HandlebarsMain
            ) {
                window.Handlebars=HandlebarsMain;
                var jsfiles = <?php echo '["https://libraries.unbxdapi.com/unbxdAutosuggest_v1.js","' . $configuration["autoSuggest"]["jsUrl"] . '"]' ?>;
            jsfiles.forEach(function(file,index) {
                    var s1 = document.createElement('script');
                    s1.type = 'text/javascript';

                    s1.src = file;
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(s1);

                });
                var asDiv = document.createElement('div');
                asDiv.id="search_bar_container";
                (document.getElementsByTagName('body')[0]).appendChild(asDiv);
                var ubx = document.createElement('link'); ubx.rel = 'stylesheet';
                ubx.href = "<?php echo $configuration["autoSuggest"]["cssUrl"]; ?>";
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ubx);
                jQueryMain(document).ready(function(){
                window.magento_unbxd_asconfig=<?php echo $block->getAutoSuggestConfig(); ?>;
                });

            }
        );

</script>
<?php endif;?>



<?php /** Unbxd Search/Browse section */
$isSearchenabled = $block->isSearchEnabled();
$isCategoryenabled = $block->isCategoryEnabled();
if ($isSearchenabled || $isCategoryenabled): ?>
<script type="text/javascript">
const checkMobile = () => {
    const w = window.innerWidth;
    if (w < 980) {
      return true;
    }
    return false;
  };

const getGridCount = function() {
  return 1;
};
const getView = () => {
  const w = window.innerWidth;
  if (w < 980) {
    return "LIST";
  }
  return "GRID";
};
</script>
<script type="text/javascript">
require(
            [
                'jquery',
                'handlebars'
            ],
            function (
                jQueryMain,
                HandlebarsMain,
            ) {
                window.Handlebars=HandlebarsMain;
                var jsfiles = <?php echo '["' . $configuration["search"]["jsUrl"] . '"]' ?>;
		        
            jsfiles.forEach(function(file,index) {
                    var s1 = document.createElement('script');
                    s1.type = 'text/javascript';

                    s1.src = file;
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(s1);

                });
                var ubx = document.createElement('link'); ubx.rel = 'stylesheet';
                ubx.href = "<?php echo $configuration["search"]["cssUrl"]; ?>";
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ubx);
                jQueryMain(document).ready(function(){
                    window.magento_unbxd_listingconfig=<?php echo ($isCategoryenabled ? $block->getCategoryConfig() : $block->getSearchConfig()); ?>;
                });
            }
        );

</script>
<?php endif;?>



