<?php ?>

<?php
/** @var \Unbxd\SearchJs\Block\Category\ProductResult $block */
    $catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
    $categoryObject = $catalogHelperData->getCategory();
    $categoryBreadCrumbPath = $catalogHelperData->getBreadcrumbPath();
    $categoryId = $categoryObject->getId();
    $categoryName = $categoryObject->getName();
    $categoryPath = $categoryObject->getPath();
    $useCategoryId = $block->useCategoryIDForBrowse();

?>
<?php
if($useCategoryId):
?>
<script type="text/javascript">
    require(['jquery'], function($){
        UnbxdAnalyticsConf = { page_type : 'BOOLEAN' , page : <?php $path=$categoryId; echo '"categoryPath:\"'.$path.'\""'; ?>, id : <?php echo $categoryId; ?> }
    });
</script>
<?php endif;?>
<?php
if(!$useCategoryId):
    ?>
    <script type="text/javascript">
        require(['jquery'], function($){
            UnbxdAnalyticsConf = { page_type : 'BOOLEAN' , page : <?php $path=""; $first=true; foreach ($categoryBreadCrumbPath as $entry) { $path = $path .(!$first ? '>' : '') .$entry['label'];$first=false;} echo '"categoryPath:\"'.$path.'\""'; ?>, id : <?php echo $categoryId; ?> }
        });
    </script>
<?php endif;?>
<input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
<div class="UNX-results-container">
      <div class="UNX-head-wrapper">
        <div>
          <div class="UNX-bread-wrapper" id="breadcrumpContainer"></div>
          <div
            class="UNX-selected-facet-wrapper"
            id="selectedFacetWrapper"
          ></div>
        </div>
        <div class="UNX-product-type-block" id="productViewTypeContainer"></div>
      </div>
      <div class="UNX-product-results">
        <div class="UNX-facet-wrapper">
          <div class="UNX-fxd-facet">
            <div class="UNX-multilevel-block" id="bucketedFacetWrapper"></div>
            <div class="UNX-text-facet-block" id="facetsWrapper"></div>
            <div class="UNX-range-block" id="rangeFacetWrapper"></div>
            <div class="UNX-m-facet-row">
              <button
                data-action="applyFacets"
                class="UNX-primary-btn UNX-facet-trigger"
              >
                Apply
              </button>
              <button
                data-action="clearFacets"
                class="UNX-default-btn UNX-facet-trigger"
              >
                Clear
              </button>
            </div>
          </div>
          <div class="UNX-m-facet-row">
            <button
              class="UNX-m-facet-btn UNX-facet-trigger fa fa-filter"
            >Filter</button>
          </div>
        </div>
        <div class="UNX-product-list">
          <div class="UNX-result-header">
            <div id="didYouMeanWrapper"></div>
            <div class="UNX-result-right">
              <div class="UNX-change-products" id="changeNoOfProducts"></div>
              <div class="UNX-sort-wrapper" id="sortWrapper"></div>
              <div
                class="UNX-change-pagination-wrap"
                id="paginationContainer"
              ></div>
              <div id="" class="UNX-change-pagination-wrap unxPagination"></div>
            </div>
          </div>
          <div id="bannerContainer"></div>
          <div class="UNX-product-wrapper" id="searchResultsWrapper"></div>
          <div id="" class="UNX-change-pagination-wrap unxPagination"></div>
        </div>
      </div>
      <div id="loaderEl"></div>
      <div id="noResultWrapper"></div>
      <div id="clickScrollContainer"></div>
    </div>
